version: "3"

services:
  workspace:
    container_name: haskell-dev
    build :
      context: .
      dockerfile: Dockerfile
      args:
        - VARIANT=8.10.2
    tty: true
    volumes:
      - ../:/workspace
    working_dir: /workspace
    user: vscode